In [169]:
from keras.layers.normalization import BatchNormalization
from keras.preprocessing.image import load_img,img_to_array
from sklearn.metrics import mean_squared_error
from keras.initializers import RandomNormal
from keras.applications.vgg16 import VGG16
from keras.optimizers import SGD
from keras.models import Model,Sequential
from keras.layers import *
from keras import backend as K
from keras.models import model_from_json
from matplotlib import cm as CM
import matplotlib.pyplot as plt
import tensorflow as tf
from tqdm import tqdm
import scipy.io as io
from PIL import Image
import PIL
import h5py
import os
import glob
import cv2
import random
import math
import sys
import numpy as np

In [2]:
!pip install opencv-python

In [170]:
K.clear_session()
root = 'data'

In [171]:
part_A_train = os.path.join(root,'part_A_final/train_data','images')
part_A_test = os.path.join(root,'part_A_final/test_data','images')
part_B_train = os.path.join(root,'part_B_final/train_data','images')
part_B_test = os.path.join(root,'part_B_final/test_data','images')
temp = 'test_images'
path_sets = [part_A_train,part_B_train]

In [172]:
img_paths = []

for path in path_sets:
    
    for img_path in glob.glob(os.path.join(path, '*.jpg')):
        
        img_paths.append(str(img_path))
        
print("Total images : ",len(img_paths))

Total images :  700


In [173]:
img_paths = []
for path in path_sets:
    for img_path in glob.glob(os.path.join(path, '*.jpg')):
        img_paths.append(img_path)
print(len(img_paths))

700


In [227]:
def create_img(path):
    #Function to load,normalize and return image 
    im = Image.open(path).convert('RGB')
    
    im = np.array(im)
    
    im = im/255.0
    
    im[:,:,0]=(im[:,:,0]-0.485)/0.229
    im[:,:,1]=(im[:,:,1]-0.456)/0.224
    im[:,:,2]=(im[:,:,2]-0.406)/0.225

    print(im.shape)
   # im = np.expand_dims(im,axis  = 0)
    print(im.shape)
    
    return im

def get_input(path):
    path = path[0] 
    img = create_img(path)
    return(img)
    
    
    
def get_output(path):
    #import target
    #resize target
    
    gt_file = h5py.File(path,'r')
    
    target = np.asarray(gt_file['density'])
    
    img = cv2.resize(target,(int(target.shape[1]/8),int(target.shape[0]/8)),interpolation = cv2.INTER_CUBIC)*64
    type(img)
    img = np.expand_dims(img,axis  = 2)       #default 3

    print(img.shape)
    
    return img
    
    
    
def preprocess_input(image,target):
    #crop image
    #crop target
    #resize target
    crop_size = (int(image.shape[0]/2),int(image.shape[1]/2))
    
    
    if random.randint(0,9)<= -1:            
            dx = int(random.randint(0,1)*image.shape[0]*1./2)
            dy = int(random.randint(0,1)*image.shape[1]*1./2)
    else:
            dx = int(random.random()*image.shape[0]*1./2)
            dy = int(random.random()*image.shape[1]*1./2)

    #print(crop_size , dx , dy)
    img = image[dx : crop_size[0]+dx , dy:crop_size[1]+dy]
    
    target_aug = target[dx:crop_size[0]+dx,dy:crop_size[1]+dy]
    print(img.shape)

    return(img,target_aug)
    
   

In [215]:
#Image data generator 
def image_generator(files, batch_size = 64):
    
    while True:
        
        input_path = np.random.choice(a = files, size = batch_size)
        
        
        batch_input = []
        batch_output = [] 
          
        #for input_path in batch_paths:
        
        inputt = get_input(input_path )
        
        output = get_output(input_path[0].replace('.jpg','.h5').replace('images','ground') )
            
       
        batch_input += [inputt]
        batch_output += [output]
    

        batch_x = np.array( batch_input )
        batch_y = np.array( batch_output )
        
        yield( batch_x, batch_y )


In [99]:
#############################

In [216]:
def save_mod(model , str1 , str2):
    model.save_weights(str1)
    
    model_json = model.to_json()
    
    with open(str2, "w") as json_file:
        json_file.write(model_json)

In [217]:
def init_weights_vgg(model):
    #vgg =  VGG16(weights='imagenet', include_top=False)
    
    json_file = open('models/VGG_16.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)
    loaded_model.load_weights("weights/VGG_16.h5")
    
    vgg = loaded_model
    
    vgg_weights=[]                         
    for layer in vgg.layers:
        if('conv' in layer.name):
            vgg_weights.append(layer.get_weights())
    
    
    offset=0
    i=0
    while(i<10):
        if('conv' in model.layers[i+offset].name):
            model.layers[i+offset].set_weights(vgg_weights[i])
            i=i+1
            #print('h')
            
        else:
            offset=offset+1

    return (model)
    

In [218]:
def euclidean_distance_loss(y_true, y_pred):
    # Euclidean distance as a measure of loss (Loss function) 
    return K.sqrt(K.sum(K.square(y_pred - y_true), axis=-1))


In [ ]:
#             else:
#                 model.add(Conv2D(64, kernel_size = kernel,activation = 'relu', padding='same',input_shape = (rows, cols, 3), kernel_initializer = init))
#                 model.add(Conv2D(64, kernel_size = kernel,activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(MaxPooling2D(strides=2))
#                 model.add(Conv2D(128,kernel_size = kernel, activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(Conv2D(128,kernel_size = kernel, activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(MaxPooling2D(strides=2))
#                 model.add(Conv2D(256,kernel_size = kernel, activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(Conv2D(256,kernel_size = kernel, activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(Conv2D(256,kernel_size = kernel, activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(MaxPooling2D(strides=2))            
#                 model.add(Conv2D(512, kernel_size = kernel,activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(Conv2D(512, kernel_size = kernel,activation = 'relu', padding='same', kernel_initializer = init))
#                 model.add(Conv2D(512, kernel_size = kernel,activation = 'relu', padding='same', kernel_initializer = init))
                

In [228]:
# Neural network model : VGG + Conv
def CrowdNet():  
            #Variable Input Size
            rows = None
            cols = None
            
            #Batch Normalisation option
            
            batch_norm = 0      #default 0 ---sudeep
            kernel = (3, 3)
            init = RandomNormal(stddev=0.01)
            model = Sequential() 
            
            #custom VGG:
            
            if(batch_norm):
                model.add(Conv2D(64, kernel_size = kernel, input_shape = (rows,cols,3),activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(Conv2D(64, kernel_size = kernel,activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(MaxPooling2D(strides=2))
                model.add(Conv2D(128,kernel_size = kernel, activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(Conv2D(128,kernel_size = kernel, activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(MaxPooling2D(strides=2))
                model.add(Conv2D(256,kernel_size = kernel, activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(Conv2D(256,kernel_size = kernel, activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(Conv2D(256,kernel_size = kernel, activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(MaxPooling2D(strides=2))            
                model.add(Conv2D(512, kernel_size = kernel,activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(Conv2D(512, kernel_size = kernel,activation = 'relu', padding='same'))
                model.add(BatchNormalization())
                model.add(Conv2D(512, kernel_size = kernel,activation = 'relu', padding='same'))
                model.add(BatchNormalization())

                
            #Conv2D          ----------by sudeep 2nd field (2,2) works
            model.add(Conv2D(512, (3, 3), activation='relu', dilation_rate = 2, kernel_initializer = init, padding = 'same'))
            model.add(Conv2D(512, (3, 3), activation='relu', dilation_rate = 2, kernel_initializer = init, padding = 'same'))
            model.add(Conv2D(512, (3, 3), activation='relu', dilation_rate = 2, kernel_initializer = init, padding = 'same'))
            model.add(Conv2D(256, (3, 3), activation='relu', dilation_rate = 2, kernel_initializer = init, padding = 'same'))
            model.add(Conv2D(128, (3, 3), activation='relu', dilation_rate = 2, kernel_initializer = init, padding = 'same'))
            model.add(Conv2D(64, (3, 3), activation='relu', dilation_rate = 2, kernel_initializer = init, padding = 'same'))
            model.add(Conv2D(1, (1, 1), dilation_rate = 1, kernel_initializer = init, padding = 'same'))
           
            
            sgd = SGD(lr = 1e-7, decay = (5*1e-4), momentum = 0.95)
            model.compile(optimizer=sgd, loss=euclidean_distance_loss, metrics=['mse'])
            
            model = init_weights_vgg(model)
            
            return model

In [229]:
model = CrowdNet()

In [230]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_35 (Conv2D)           (None, None, None, 64)    1792      
_________________________________________________________________
conv2d_36 (Conv2D)           (None, None, None, 64)    36928     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, None, None, 64)    0         
_________________________________________________________________
conv2d_37 (Conv2D)           (None, None, None, 128)   73856     
_________________________________________________________________
conv2d_38 (Conv2D)           (None, None, None, 128)   147584    
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, None, None, 128)   0         
_________________________________________________________________
conv2d_39 (Conv2D)           (None, None, None, 256)  

In [231]:
train_gen = image_generator(img_paths,1)

In [232]:
img_paths

['data\\part_A_final/test_data\\images\\IMG_1.jpg',
 'data\\part_A_final/test_data\\images\\IMG_10.jpg',
 'data\\part_A_final/test_data\\images\\IMG_100.jpg',
 'data\\part_A_final/test_data\\images\\IMG_101.jpg',
 'data\\part_A_final/test_data\\images\\IMG_102.jpg',
 'data\\part_A_final/test_data\\images\\IMG_103.jpg',
 'data\\part_A_final/test_data\\images\\IMG_104.jpg',
 'data\\part_A_final/test_data\\images\\IMG_105.jpg',
 'data\\part_A_final/test_data\\images\\IMG_106.jpg',
 'data\\part_A_final/test_data\\images\\IMG_107.jpg',
 'data\\part_A_final/test_data\\images\\IMG_108.jpg',
 'data\\part_A_final/test_data\\images\\IMG_109.jpg',
 'data\\part_A_final/test_data\\images\\IMG_11.jpg',
 'data\\part_A_final/test_data\\images\\IMG_110.jpg',
 'data\\part_A_final/test_data\\images\\IMG_111.jpg',
 'data\\part_A_final/test_data\\images\\IMG_112.jpg',
 'data\\part_A_final/test_data\\images\\IMG_113.jpg',
 'data\\part_A_final/test_data\\images\\IMG_114.jpg',
 'data\\part_A_final/test_data\\

In [233]:
sgd = SGD(lr = 1e-7, decay = (5*1e-4), momentum = 0.95)
model.compile(optimizer=sgd, loss=euclidean_distance_loss, metrics=['accuracy'])

In [26]:
model.fit_generator(train_gen,epochs=3, steps_per_epoch=700 , verbose=True,max_queue_size=1)

NameError: name 'model' is not defined

In [186]:
save_mod(model,"weights/model_A_weights.h5","models/Model.json")

# Analysis of the model

In [1]:
from keras.models import model_from_json
import os
import cv2
import glob
import h5py
import pandas as pd
from sklearn.metrics import mean_absolute_error
import scipy.io as io
from PIL import Image
import numpy as np

Using TensorFlow backend.


In [10]:
def load_model():
    
    json_file = open('models/Model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)
    loaded_model.load_weights("weights/model_A_weights.h5")
    return loaded_model


def create_img(path):
    im = Image.open(path).convert('RGB')
    
    im = np.array(im)
    
    im = im/255.0
    
    im[:,:,0]=(im[:,:,0]-0.485)/0.229
    im[:,:,1]=(im[:,:,1]-0.456)/0.224
    im[:,:,2]=(im[:,:,2]-0.406)/0.225


    im = np.expand_dims(im,axis  = 0)
    return im

In [3]:
root = 'data'

In [5]:

part_A_train = os.path.join(root,'part_A_final/train_data','images')
part_A_test = os.path.join(root,'part_A_final/test_data','images')
part_B_train = os.path.join(root,'part_B_final/train_data','images')
part_B_test = os.path.join(root,'part_B_final/test_data','images')
path_sets = [part_B_test] # to test on full test dataset
# path_sets = [part_A_train,part_B_train]

In [6]:

img_paths = []
for path in path_sets:
    for img_path in glob.glob(os.path.join(path, '*.jpg')):
        img_paths.append(img_path)
print(len(img_paths))

316


In [7]:
print(len(img_paths))

316


In [11]:
model_analysis = load_model()
name = []
y_true = []
y_pred = []


In [13]:
model_analysis.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, None, None, 64)    1792      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, None, None, 64)    36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, None, None, 64)    0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, None, None, 128)   73856     
_________________________________________________________________
conv2d_4 (Conv2D)            (None, None, None, 128)   147584    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, None, None, 128)   0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, None, None, 256)  

In [15]:

for image in img_paths:
    name.append(image)
    gt = h5py.File(image.replace('.jpg','.h5').replace('images','ground') )
    groundtruth = np.asarray(gt['density'])
    num1 = np.sum(groundtruth)
    y_true.append(np.sum(num1))
    img = create_img(image)
    #print(img)
    # Getting count
    image_sum = model_analysis.predict(img)
    print(image_sum)
    num = np.sum(image_sum)
#    print(num)
    y_pred.append(np.sum(num))

    
data = pd.DataFrame({'name': name,'y_pred': y_pred,'y_true': y_true})
data.to_csv('CSV/A_on_A_test.csv', sep=',')

C:\Users\sudee\anaconda3\lib\site-packages\ipykernel_launcher.py:3: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  This is separate from the ipykernel package so we can avoid doing imports until


[[[[0.00070822]
   [0.00082004]
   [0.00067159]
   ...
   [0.00070166]
   [0.00071382]
   [0.00087435]]

  [[0.00074796]
   [0.00063897]
   [0.00076423]
   ...
   [0.00055305]
   [0.00073064]
   [0.00064781]]

  [[0.00103571]
   [0.00097153]
   [0.00083712]
   ...
   [0.00052565]
   [0.00141307]
   [0.00079544]]

  ...

  [[0.00078803]
   [0.00075112]
   [0.00098795]
   ...
   [0.00045817]
   [0.00075038]
   [0.00065024]]

  [[0.00093786]
   [0.00089875]
   [0.00087542]
   ...
   [0.00064451]
   [0.00100869]
   [0.00098201]]

  [[0.00095039]
   [0.00098912]
   [0.00089292]
   ...
   [0.00065456]
   [0.00073388]
   [0.00094353]]]]
[[[[0.00077779]
   [0.0011451 ]
   [0.00098934]
   ...
   [0.0006861 ]
   [0.00072916]
   [0.00080992]]

  [[0.00064169]
   [0.0009522 ]
   [0.00063175]
   ...
   [0.00077618]
   [0.00092218]
   [0.0008392 ]]

  [[0.00053585]
   [0.00085097]
   [0.00046159]
   ...
   [0.00067248]
   [0.00167414]
   [0.00096005]]

  ...

  [[0.00053665]
   [0.00018981]
   [0.00

[[[[0.00086838]
   [0.00098413]
   [0.00100507]
   ...
   [0.00081467]
   [0.00072667]
   [0.00082529]]

  [[0.00093368]
   [0.00089741]
   [0.00099909]
   ...
   [0.0007853 ]
   [0.00082623]
   [0.00090708]]

  [[0.00091229]
   [0.00123163]
   [0.00105919]
   ...
   [0.00072078]
   [0.00085417]
   [0.00103047]]

  ...

  [[0.00092284]
   [0.00091488]
   [0.00065489]
   ...
   [0.00084667]
   [0.00088958]
   [0.00095675]]

  [[0.00097474]
   [0.00090402]
   [0.00107042]
   ...
   [0.00094348]
   [0.00089504]
   [0.00079899]]

  [[0.00061399]
   [0.00088637]
   [0.00078474]
   ...
   [0.00068439]
   [0.00088487]
   [0.00098574]]]]
[[[[0.00090086]
   [0.0009334 ]
   [0.00097311]
   ...
   [0.00103815]
   [0.00092037]
   [0.00089981]]

  [[0.00088793]
   [0.00079159]
   [0.00085171]
   ...
   [0.00068437]
   [0.00069729]
   [0.00075019]]

  [[0.00082368]
   [0.00090303]
   [0.00099989]
   ...
   [0.00067483]
   [0.00124717]
   [0.000903  ]]

  ...

  [[0.00056531]
   [0.00066649]
   [0.00

[[[[0.00073686]
   [0.00083878]
   [0.00112704]
   ...
   [0.00076736]
   [0.00074635]
   [0.0008781 ]]

  [[0.00057955]
   [0.00062916]
   [0.00086989]
   ...
   [0.00079926]
   [0.00078001]
   [0.0009414 ]]

  [[0.00105753]
   [0.00094174]
   [0.00041449]
   ...
   [0.00027491]
   [0.0005727 ]
   [0.00094442]]

  ...

  [[0.00115008]
   [0.0008391 ]
   [0.00070782]
   ...
   [0.00046014]
   [0.00078913]
   [0.00097676]]

  [[0.00104373]
   [0.00093641]
   [0.0005639 ]
   ...
   [0.00056725]
   [0.00078889]
   [0.00106745]]

  [[0.00112915]
   [0.00082978]
   [0.0002463 ]
   ...
   [0.00058642]
   [0.00078228]
   [0.00084686]]]]
[[[[9.8295847e-04]
   [1.0109524e-03]
   [9.6112874e-04]
   ...
   [1.1521039e-03]
   [6.7814288e-04]
   [5.1587616e-04]]

  [[9.4627216e-04]
   [9.1442658e-04]
   [7.8025961e-04]
   ...
   [8.9760160e-04]
   [7.3325349e-04]
   [7.7155471e-04]]

  [[1.0169072e-03]
   [1.2153953e-03]
   [5.6067976e-04]
   ...
   [4.5486318e-05]
   [5.7828880e-04]
   [1.1933249e

[[[[0.00077725]
   [0.00073965]
   [0.00057369]
   ...
   [0.0007039 ]
   [0.00076045]
   [0.00097658]]

  [[0.00088828]
   [0.00066415]
   [0.00104314]
   ...
   [0.00066729]
   [0.00067838]
   [0.00103008]]

  [[0.00090359]
   [0.0009118 ]
   [0.00089883]
   ...
   [0.00042962]
   [0.00093433]
   [0.00126234]]

  ...

  [[0.00040896]
   [0.00034874]
   [0.00027746]
   ...
   [0.00091101]
   [0.00090981]
   [0.0010932 ]]

  [[0.00100582]
   [0.00081563]
   [0.00059224]
   ...
   [0.00062034]
   [0.0009049 ]
   [0.00098909]]

  [[0.00098245]
   [0.00085283]
   [0.00063929]
   ...
   [0.00068182]
   [0.00112092]
   [0.00083911]]]]
[[[[0.00075139]
   [0.00078539]
   [0.00054858]
   ...
   [0.00087498]
   [0.00065107]
   [0.0006775 ]]

  [[0.00066905]
   [0.00073425]
   [0.00046592]
   ...
   [0.00091432]
   [0.00066104]
   [0.0005393 ]]

  [[0.00073789]
   [0.00064462]
   [0.00034473]
   ...
   [0.00082145]
   [0.00137594]
   [0.0008415 ]]

  ...

  [[0.00080169]
   [0.00084581]
   [0.00

[[[[0.00092785]
   [0.00081237]
   [0.00070336]
   ...
   [0.00111809]
   [0.00078559]
   [0.00087085]]

  [[0.00087134]
   [0.00082337]
   [0.00089696]
   ...
   [0.00102272]
   [0.0009797 ]
   [0.00091811]]

  [[0.00089027]
   [0.00102536]
   [0.00043643]
   ...
   [0.0013039 ]
   [0.00093564]
   [0.00070661]]

  ...

  [[0.00067916]
   [0.00072504]
   [0.00107686]
   ...
   [0.00012507]
   [0.00067973]
   [0.00092449]]

  [[0.0008508 ]
   [0.00090345]
   [0.00080491]
   ...
   [0.00046589]
   [0.00085818]
   [0.00065604]]

  [[0.00092469]
   [0.00089458]
   [0.00070423]
   ...
   [0.00083266]
   [0.0008119 ]
   [0.00090591]]]]
[[[[0.00043629]
   [0.00094541]
   [0.00063009]
   ...
   [0.00130022]
   [0.00090775]
   [0.00109361]]

  [[0.00088331]
   [0.0010002 ]
   [0.00070674]
   ...
   [0.00079546]
   [0.00105702]
   [0.00092933]]

  [[0.00103477]
   [0.00104138]
   [0.0004823 ]
   ...
   [0.00080746]
   [0.00120342]
   [0.00100615]]

  ...

  [[0.00085316]
   [0.0007519 ]
   [0.00

[[[[0.00080415]
   [0.00083342]
   [0.00068042]
   ...
   [0.00076209]
   [0.00062117]
   [0.00101191]]

  [[0.00077045]
   [0.00077898]
   [0.00092853]
   ...
   [0.0008818 ]
   [0.00073392]
   [0.00056234]]

  [[0.00064424]
   [0.00048991]
   [0.00062931]
   ...
   [0.00051694]
   [0.00079063]
   [0.00069736]]

  ...

  [[0.00071763]
   [0.00067008]
   [0.00071762]
   ...
   [0.000675  ]
   [0.00097314]
   [0.00098327]]

  [[0.00097031]
   [0.00087429]
   [0.00078067]
   ...
   [0.00086704]
   [0.00097417]
   [0.00098872]]

  [[0.0008494 ]
   [0.00088361]
   [0.00093287]
   ...
   [0.00055591]
   [0.0008943 ]
   [0.00089381]]]]
[[[[0.00074952]
   [0.00098782]
   [0.00070343]
   ...
   [0.00106949]
   [0.00065616]
   [0.00046408]]

  [[0.00078693]
   [0.00089432]
   [0.00067489]
   ...
   [0.00112167]
   [0.00075738]
   [0.00069238]]

  [[0.00108519]
   [0.00107328]
   [0.00093443]
   ...
   [0.00096428]
   [0.00099204]
   [0.00095616]]

  ...

  [[0.00101202]
   [0.00088674]
   [0.00

[[[[7.1431603e-04]
   [7.3425256e-04]
   [7.2287640e-04]
   ...
   [9.0279634e-04]
   [9.6717541e-04]
   [1.2414649e-03]]

  [[8.3274447e-04]
   [8.5209013e-04]
   [6.8366161e-04]
   ...
   [7.2945101e-04]
   [7.6761225e-04]
   [8.7423943e-04]]

  [[4.9805280e-04]
   [5.0678209e-04]
   [7.5166987e-05]
   ...
   [1.5427929e-03]
   [1.1505072e-03]
   [1.2018033e-03]]

  ...

  [[8.7695761e-04]
   [9.0670952e-04]
   [9.9701399e-04]
   ...
   [4.9457408e-04]
   [8.0374634e-04]
   [6.8700092e-04]]

  [[8.8387902e-04]
   [9.2307123e-04]
   [7.7275047e-04]
   ...
   [6.5111736e-04]
   [8.2978932e-04]
   [8.1807841e-04]]

  [[9.4260485e-04]
   [9.0284919e-04]
   [6.4797222e-04]
   ...
   [9.2453480e-04]
   [8.3841843e-04]
   [5.7643634e-04]]]]
[[[[0.00058275]
   [0.00078792]
   [0.00054952]
   ...
   [0.00074432]
   [0.00085539]
   [0.00120401]]

  [[0.0008335 ]
   [0.00095086]
   [0.00096175]
   ...
   [0.00058691]
   [0.00100041]
   [0.00117564]]

  [[0.00093085]
   [0.00100173]
   [0.000791

[[[[0.00075644]
   [0.00066994]
   [0.00117548]
   ...
   [0.00070748]
   [0.0006128 ]
   [0.00086079]]

  [[0.00062707]
   [0.00062076]
   [0.00093221]
   ...
   [0.00045121]
   [0.00085835]
   [0.00075252]]

  [[0.00065549]
   [0.00098269]
   [0.00118899]
   ...
   [0.00013218]
   [0.0008528 ]
   [0.00105327]]

  ...

  [[0.00089643]
   [0.00084824]
   [0.0007265 ]
   ...
   [0.00073456]
   [0.00091787]
   [0.00096307]]

  [[0.00086689]
   [0.000916  ]
   [0.00086092]
   ...
   [0.00064536]
   [0.00080284]
   [0.00077377]]

  [[0.00096232]
   [0.00101038]
   [0.00077798]
   ...
   [0.00079138]
   [0.00078779]
   [0.00062297]]]]
[[[[0.00060463]
   [0.00062724]
   [0.00063476]
   ...
   [0.00107757]
   [0.00059992]
   [0.00055742]]

  [[0.00068361]
   [0.00084734]
   [0.00100584]
   ...
   [0.00104534]
   [0.00066051]
   [0.00076556]]

  [[0.00050327]
   [0.00084774]
   [0.00077557]
   ...
   [0.00101296]
   [0.00096342]
   [0.00100205]]

  ...

  [[0.00101616]
   [0.00085037]
   [0.00

[[[[0.00073582]
   [0.00072567]
   [0.00083716]
   ...
   [0.0008156 ]
   [0.00095203]
   [0.00089106]]

  [[0.00073796]
   [0.00086782]
   [0.00098017]
   ...
   [0.00073038]
   [0.00098206]
   [0.00107003]]

  [[0.00066333]
   [0.00101952]
   [0.00101437]
   ...
   [0.00109721]
   [0.00128809]
   [0.0011383 ]]

  ...

  [[0.00089412]
   [0.00087851]
   [0.00092778]
   ...
   [0.00053273]
   [0.00084384]
   [0.00068818]]

  [[0.00102128]
   [0.00112775]
   [0.00093778]
   ...
   [0.00043816]
   [0.00077081]
   [0.00082617]]

  [[0.00077588]
   [0.00094839]
   [0.00112989]
   ...
   [0.0004175 ]
   [0.00073841]
   [0.00060833]]]]
[[[[0.00080962]
   [0.00101974]
   [0.00087836]
   ...
   [0.00085737]
   [0.00088587]
   [0.00090304]]

  [[0.00087614]
   [0.00093346]
   [0.00085353]
   ...
   [0.00087846]
   [0.00071916]
   [0.00077938]]

  [[0.00087936]
   [0.00106817]
   [0.00085944]
   ...
   [0.00105178]
   [0.00110474]
   [0.00095985]]

  ...

  [[0.00092696]
   [0.00090425]
   [0.00

[[[[0.00075887]
   [0.00073366]
   [0.00089602]
   ...
   [0.00064689]
   [0.00083779]
   [0.00074062]]

  [[0.00096435]
   [0.00091998]
   [0.00072135]
   ...
   [0.00076475]
   [0.00093892]
   [0.00078182]]

  [[0.00100096]
   [0.00104205]
   [0.00080451]
   ...
   [0.00103215]
   [0.00088462]
   [0.00104167]]

  ...

  [[0.00086355]
   [0.00075214]
   [0.00119192]
   ...
   [0.00109655]
   [0.00113939]
   [0.00111341]]

  [[0.00077143]
   [0.00075036]
   [0.00095013]
   ...
   [0.00051921]
   [0.00091662]
   [0.00099167]]

  [[0.00098759]
   [0.00094794]
   [0.00081891]
   ...
   [0.00012547]
   [0.00096484]
   [0.00097437]]]]
[[[[7.9797173e-04]
   [7.6652644e-04]
   [8.8397815e-04]
   ...
   [8.6222781e-04]
   [9.3853957e-04]
   [6.2259019e-04]]

  [[8.1640325e-04]
   [8.9398661e-04]
   [7.7175867e-04]
   ...
   [7.7485701e-04]
   [1.0131369e-03]
   [8.4005814e-04]]

  [[1.0416199e-03]
   [1.0839241e-03]
   [5.9889321e-04]
   ...
   [1.0337381e-03]
   [1.3282915e-03]
   [1.2896480e

[[[[0.00062551]
   [0.00082358]
   [0.00096016]
   ...
   [0.00071935]
   [0.00081958]
   [0.00092347]]

  [[0.00085599]
   [0.00077345]
   [0.00073036]
   ...
   [0.00088421]
   [0.0008564 ]
   [0.00096538]]

  [[0.00082757]
   [0.00076806]
   [0.00070973]
   ...
   [0.00048407]
   [0.00074536]
   [0.00117045]]

  ...

  [[0.0008453 ]
   [0.00076293]
   [0.00089148]
   ...
   [0.00091862]
   [0.00098748]
   [0.00077266]]

  [[0.00094411]
   [0.00102282]
   [0.00065893]
   ...
   [0.00057592]
   [0.00087507]
   [0.0010756 ]]

  [[0.0010351 ]
   [0.00088567]
   [0.00072098]
   ...
   [0.00035532]
   [0.00074093]
   [0.00070811]]]]
[[[[ 8.8197278e-04]
   [ 8.3107076e-04]
   [ 8.5360714e-04]
   ...
   [ 9.6456218e-04]
   [ 1.1213666e-03]
   [ 7.5849495e-04]]

  [[ 9.8605000e-04]
   [ 8.6718623e-04]
   [ 7.5148582e-04]
   ...
   [ 9.2439330e-04]
   [ 7.6701381e-04]
   [ 7.1417855e-04]]

  [[ 7.7829266e-04]
   [ 8.7843451e-04]
   [ 5.2268745e-04]
   ...
   [ 6.5109029e-04]
   [ 9.2253106e-0

[[[[0.00035152]
   [0.00053499]
   [0.00075901]
   ...
   [0.00118414]
   [0.00072279]
   [0.00099847]]

  [[0.00057018]
   [0.00049565]
   [0.00045351]
   ...
   [0.00119287]
   [0.00087423]
   [0.00110598]]

  [[0.0007256 ]
   [0.00094622]
   [0.00029009]
   ...
   [0.00090144]
   [0.000874  ]
   [0.00113643]]

  ...

  [[0.00074613]
   [0.00090251]
   [0.00095422]
   ...
   [0.0004589 ]
   [0.00079967]
   [0.00069991]]

  [[0.00074475]
   [0.00094772]
   [0.00065044]
   ...
   [0.00057081]
   [0.00080289]
   [0.00088129]]

  [[0.00094628]
   [0.0009674 ]
   [0.00068067]
   ...
   [0.00033539]
   [0.00089795]
   [0.0008821 ]]]]
[[[[0.00064081]
   [0.00068241]
   [0.00054531]
   ...
   [0.00095066]
   [0.00116582]
   [0.00069058]]

  [[0.00055001]
   [0.00065875]
   [0.00067721]
   ...
   [0.00101586]
   [0.00096918]
   [0.0007125 ]]

  [[0.0005559 ]
   [0.001309  ]
   [0.00142197]
   ...
   [0.00039786]
   [0.00081511]
   [0.0006688 ]]

  ...

  [[0.00074593]
   [0.00089765]
   [0.00

[[[[ 0.00069119]
   [ 0.0006827 ]
   [ 0.00084772]
   ...
   [ 0.00043955]
   [ 0.00069178]
   [ 0.00066389]]

  [[ 0.00074097]
   [ 0.00079134]
   [ 0.0006962 ]
   ...
   [ 0.00076082]
   [ 0.00076629]
   [ 0.00087362]]

  [[ 0.0010507 ]
   [ 0.00091316]
   [ 0.00072997]
   ...
   [-0.00010632]
   [ 0.00112016]
   [ 0.00125321]]

  ...

  [[ 0.00098609]
   [ 0.00070884]
   [ 0.00068286]
   ...
   [ 0.0006269 ]
   [ 0.0008118 ]
   [ 0.0007742 ]]

  [[ 0.00080874]
   [ 0.00079026]
   [ 0.00076659]
   ...
   [ 0.00078719]
   [ 0.00095493]
   [ 0.00090941]]

  [[ 0.00074586]
   [ 0.00078225]
   [ 0.0005303 ]
   ...
   [ 0.00047035]
   [ 0.00084026]
   [ 0.00088338]]]]
[[[[8.4798841e-05]
   [3.4709246e-04]
   [3.9314321e-04]
   ...
   [8.0165546e-04]
   [7.0864661e-04]
   [7.2445034e-04]]

  [[7.8190892e-04]
   [6.8108167e-04]
   [4.2871595e-04]
   ...
   [6.4330082e-04]
   [8.7183295e-04]
   [6.7234447e-04]]

  [[8.6133380e-04]
   [9.9988247e-04]
   [8.3243765e-04]
   ...
   [8.7933039e-0

[[[[0.00097114]
   [0.0009519 ]
   [0.00090876]
   ...
   [0.0008291 ]
   [0.00084591]
   [0.00092888]]

  [[0.00097965]
   [0.00102223]
   [0.00086812]
   ...
   [0.00077247]
   [0.000762  ]
   [0.00102415]]

  [[0.00083539]
   [0.00097435]
   [0.00114329]
   ...
   [0.00063921]
   [0.00118108]
   [0.00091662]]

  ...

  [[0.0009445 ]
   [0.00087458]
   [0.00100009]
   ...
   [0.00052883]
   [0.00095212]
   [0.00093162]]

  [[0.00095209]
   [0.00097018]
   [0.0008951 ]
   ...
   [0.0006381 ]
   [0.00081924]
   [0.00093571]]

  [[0.00105879]
   [0.00105629]
   [0.00097988]
   ...
   [0.00063962]
   [0.00086012]
   [0.00083175]]]]
[[[[0.00065623]
   [0.00088113]
   [0.00106268]
   ...
   [0.00096009]
   [0.00086041]
   [0.00095233]]

  [[0.00085936]
   [0.00093311]
   [0.00086126]
   ...
   [0.00090553]
   [0.00088682]
   [0.00087942]]

  [[0.0009837 ]
   [0.00096183]
   [0.00021714]
   ...
   [0.00090981]
   [0.00119338]
   [0.00094626]]

  ...

  [[0.0007822 ]
   [0.00072679]
   [0.00

[[[[0.00067566]
   [0.00078033]
   [0.0009192 ]
   ...
   [0.00094899]
   [0.00095041]
   [0.00090075]]

  [[0.00073877]
   [0.00095141]
   [0.00080484]
   ...
   [0.00102451]
   [0.00090399]
   [0.00077853]]

  [[0.00077351]
   [0.00075065]
   [0.00071271]
   ...
   [0.00115547]
   [0.00118062]
   [0.0012206 ]]

  ...

  [[0.00077135]
   [0.00080227]
   [0.000826  ]
   ...
   [0.00046125]
   [0.00061951]
   [0.00073731]]

  [[0.00084526]
   [0.00077366]
   [0.00101043]
   ...
   [0.0009236 ]
   [0.00097469]
   [0.00082914]]

  [[0.00086051]
   [0.00090773]
   [0.00095288]
   ...
   [0.00045761]
   [0.00080803]
   [0.00083665]]]]
[[[[0.00060858]
   [0.00063591]
   [0.00049   ]
   ...
   [0.00087607]
   [0.00099596]
   [0.00077581]]

  [[0.00094859]
   [0.00101215]
   [0.0007724 ]
   ...
   [0.00056341]
   [0.0007315 ]
   [0.00071574]]

  [[0.0007979 ]
   [0.00074319]
   [0.00032846]
   ...
   [0.00052477]
   [0.00100585]
   [0.0007768 ]]

  ...

  [[0.00099243]
   [0.00084887]
   [0.00

[[[[0.00081016]
   [0.0006591 ]
   [0.00094065]
   ...
   [0.00085916]
   [0.00055671]
   [0.00102246]]

  [[0.00073801]
   [0.00073461]
   [0.00120495]
   ...
   [0.00105512]
   [0.00100935]
   [0.00096012]]

  [[0.00064566]
   [0.00081563]
   [0.00064234]
   ...
   [0.0012809 ]
   [0.00115648]
   [0.00122607]]

  ...

  [[0.00102292]
   [0.00076649]
   [0.00103925]
   ...
   [0.00047274]
   [0.00083848]
   [0.00087315]]

  [[0.00092619]
   [0.00088226]
   [0.0006243 ]
   ...
   [0.00090966]
   [0.00094046]
   [0.00092463]]

  [[0.00099517]
   [0.00104946]
   [0.00090945]
   ...
   [0.0003809 ]
   [0.0007525 ]
   [0.00086772]]]]
[[[[0.00058948]
   [0.00098459]
   [0.00064313]
   ...
   [0.00094884]
   [0.00078965]
   [0.00073251]]

  [[0.00051624]
   [0.00072981]
   [0.00074729]
   ...
   [0.00067351]
   [0.00037222]
   [0.00067231]]

  [[0.00035386]
   [0.00066763]
   [0.00061633]
   ...
   [0.00094426]
   [0.00071373]
   [0.00085842]]

  ...

  [[0.00065466]
   [0.0006938 ]
   [0.00

[[[[0.00055102]
   [0.00051341]
   [0.00025351]
   ...
   [0.00111471]
   [0.00091731]
   [0.00074398]]

  [[0.00071602]
   [0.0007349 ]
   [0.00084084]
   ...
   [0.00107214]
   [0.00067419]
   [0.00068682]]

  [[0.00097622]
   [0.00093233]
   [0.00039655]
   ...
   [0.0010832 ]
   [0.00117448]
   [0.0006571 ]]

  ...

  [[0.00065052]
   [0.00041432]
   [0.00028396]
   ...
   [0.00052397]
   [0.00081707]
   [0.00075243]]

  [[0.00064009]
   [0.00074624]
   [0.0010457 ]
   ...
   [0.00072184]
   [0.0009253 ]
   [0.00103485]]

  [[0.00095597]
   [0.0008911 ]
   [0.00070275]
   ...
   [0.00063899]
   [0.00064699]
   [0.00069102]]]]
[[[[0.00072087]
   [0.00068846]
   [0.00117086]
   ...
   [0.00094365]
   [0.00093408]
   [0.00066707]]

  [[0.0007625 ]
   [0.0008731 ]
   [0.00070944]
   ...
   [0.00103783]
   [0.00071103]
   [0.00059163]]

  [[0.00091   ]
   [0.00090974]
   [0.00071215]
   ...
   [0.00079491]
   [0.00074655]
   [0.00079707]]

  ...

  [[0.00075384]
   [0.00076049]
   [0.00

[[[[0.00054123]
   [0.00079658]
   [0.00107713]
   ...
   [0.00084489]
   [0.00044358]
   [0.0004785 ]]

  [[0.00066881]
   [0.00081378]
   [0.00080487]
   ...
   [0.00079058]
   [0.00092378]
   [0.00088952]]

  [[0.00130886]
   [0.00110997]
   [0.00067283]
   ...
   [0.00139293]
   [0.0007511 ]
   [0.00074159]]

  ...

  [[0.00061759]
   [0.00071658]
   [0.00054051]
   ...
   [0.00082281]
   [0.00089287]
   [0.00102279]]

  [[0.00087039]
   [0.0008548 ]
   [0.00077584]
   ...
   [0.0008619 ]
   [0.00097447]
   [0.00094934]]

  [[0.00076778]
   [0.00069882]
   [0.0008584 ]
   ...
   [0.00091921]
   [0.00086967]
   [0.00086614]]]]
[[[[0.00044371]
   [0.00055763]
   [0.00066543]
   ...
   [0.00089599]
   [0.00090165]
   [0.00075377]]

  [[0.00064601]
   [0.00071362]
   [0.00067943]
   ...
   [0.00070953]
   [0.00076938]
   [0.00054635]]

  [[0.00100769]
   [0.00107455]
   [0.00082491]
   ...
   [0.00063519]
   [0.00105214]
   [0.00095958]]

  ...

  [[0.00082157]
   [0.00104599]
   [0.00

[[[[0.00069899]
   [0.00071936]
   [0.00037052]
   ...
   [0.00115817]
   [0.00104769]
   [0.00097944]]

  [[0.00051658]
   [0.00065479]
   [0.00059261]
   ...
   [0.00081334]
   [0.00081522]
   [0.00092434]]

  [[0.00041574]
   [0.0009105 ]
   [0.00062907]
   ...
   [0.00074753]
   [0.00097662]
   [0.00072937]]

  ...

  [[0.00081401]
   [0.00090589]
   [0.00083408]
   ...
   [0.00029687]
   [0.00084086]
   [0.00090006]]

  [[0.00083358]
   [0.00090142]
   [0.00089722]
   ...
   [0.00065151]
   [0.00092889]
   [0.00091098]]

  [[0.00100729]
   [0.00089422]
   [0.00075195]
   ...
   [0.00063334]
   [0.00071072]
   [0.00075293]]]]
[[[[0.00086891]
   [0.00098529]
   [0.00085643]
   ...
   [0.00105658]
   [0.00077079]
   [0.00087669]]

  [[0.00098994]
   [0.000939  ]
   [0.00096853]
   ...
   [0.0008188 ]
   [0.00052415]
   [0.00086196]]

  [[0.00086713]
   [0.00080658]
   [0.00062861]
   ...
   [0.00105666]
   [0.00093447]
   [0.00102098]]

  ...

  [[0.00116994]
   [0.00065667]
   [0.00

[[[[0.00065304]
   [0.00071055]
   [0.00085103]
   ...
   [0.00107261]
   [0.00062713]
   [0.0004476 ]]

  [[0.00079945]
   [0.0006968 ]
   [0.00056919]
   ...
   [0.00077675]
   [0.00041801]
   [0.00081797]]

  [[0.00047373]
   [0.00058897]
   [0.00068642]
   ...
   [0.00062407]
   [0.00104797]
   [0.00129992]]

  ...

  [[0.00090175]
   [0.00067773]
   [0.00058316]
   ...
   [0.00076436]
   [0.00098772]
   [0.00091488]]

  [[0.00095021]
   [0.00099492]
   [0.0006993 ]
   ...
   [0.0005911 ]
   [0.00081681]
   [0.00079744]]

  [[0.00105882]
   [0.00102274]
   [0.00066962]
   ...
   [0.00054067]
   [0.00082527]
   [0.00078144]]]]
[[[[0.0007865 ]
   [0.00090901]
   [0.00069286]
   ...
   [0.00059725]
   [0.00090728]
   [0.00106321]]

  [[0.00075117]
   [0.00087976]
   [0.00100079]
   ...
   [0.00076974]
   [0.00094962]
   [0.00081341]]

  [[0.00113601]
   [0.00098259]
   [0.00050959]
   ...
   [0.00096745]
   [0.00141065]
   [0.00158829]]

  ...

  [[0.00074975]
   [0.00086287]
   [0.00

[[[[0.00095355]
   [0.0009576 ]
   [0.00089139]
   ...
   [0.00062168]
   [0.00068958]
   [0.00062479]]

  [[0.00085167]
   [0.00072384]
   [0.00074247]
   ...
   [0.00104931]
   [0.00062016]
   [0.00063638]]

  [[0.00080949]
   [0.00082438]
   [0.00071963]
   ...
   [0.00061156]
   [0.00086765]
   [0.0014378 ]]

  ...

  [[0.00068787]
   [0.00071878]
   [0.00034509]
   ...
   [0.0002458 ]
   [0.00082251]
   [0.0009646 ]]

  [[0.00054901]
   [0.00094337]
   [0.00071339]
   ...
   [0.00068866]
   [0.0005514 ]
   [0.00079462]]

  [[0.00076536]
   [0.00106043]
   [0.00097817]
   ...
   [0.00075052]
   [0.00076999]
   [0.00075799]]]]
[[[[0.00092774]
   [0.00093785]
   [0.00091244]
   ...
   [0.00090513]
   [0.00070388]
   [0.00066829]]

  [[0.00081086]
   [0.00092271]
   [0.00068734]
   ...
   [0.00085865]
   [0.00085071]
   [0.00075077]]

  [[0.00084665]
   [0.00083977]
   [0.00045212]
   ...
   [0.00070611]
   [0.0008982 ]
   [0.00096444]]

  ...

  [[0.00064782]
   [0.00044573]
   [0.00

[[[[0.00043329]
   [0.00061941]
   [0.00057739]
   ...
   [0.0009589 ]
   [0.00092928]
   [0.0008682 ]]

  [[0.00060157]
   [0.00066112]
   [0.00076013]
   ...
   [0.00107024]
   [0.00081316]
   [0.00089479]]

  [[0.00071489]
   [0.00089472]
   [0.00074218]
   ...
   [0.00067462]
   [0.0010308 ]
   [0.00112589]]

  ...

  [[0.00058041]
   [0.00079178]
   [0.00075573]
   ...
   [0.00036944]
   [0.00054405]
   [0.00040576]]

  [[0.0008833 ]
   [0.00090583]
   [0.00077256]
   ...
   [0.00025338]
   [0.00091082]
   [0.00078121]]

  [[0.00097271]
   [0.00098935]
   [0.00092453]
   ...
   [0.00035985]
   [0.00089564]
   [0.00087845]]]]
[[[[0.00098085]
   [0.00075156]
   [0.00042167]
   ...
   [0.00082705]
   [0.00077592]
   [0.00091081]]

  [[0.00068987]
   [0.00077487]
   [0.00063729]
   ...
   [0.00064034]
   [0.00071227]
   [0.00099479]]

  [[0.00076809]
   [0.0009005 ]
   [0.00056038]
   ...
   [0.00086891]
   [0.00102921]
   [0.00106213]]

  ...

  [[0.00078153]
   [0.00065638]
   [0.00

[[[[0.00090801]
   [0.0006886 ]
   [0.0008439 ]
   ...
   [0.00108237]
   [0.00072287]
   [0.0007701 ]]

  [[0.00072118]
   [0.00068803]
   [0.00050178]
   ...
   [0.00082566]
   [0.00069438]
   [0.00071586]]

  [[0.0008369 ]
   [0.00064368]
   [0.00046889]
   ...
   [0.00074566]
   [0.00085666]
   [0.00076786]]

  ...

  [[0.00084002]
   [0.00080453]
   [0.00096431]
   ...
   [0.00057052]
   [0.00065587]
   [0.00078671]]

  [[0.00089806]
   [0.00081497]
   [0.00093136]
   ...
   [0.00084297]
   [0.00087523]
   [0.0008121 ]]

  [[0.00094023]
   [0.0008881 ]
   [0.00100546]
   ...
   [0.00069712]
   [0.00088023]
   [0.0009127 ]]]]
[[[[ 7.05666665e-04]
   [ 8.32309481e-04]
   [ 8.45783856e-04]
   ...
   [ 9.84942075e-04]
   [ 8.33822240e-04]
   [ 7.22151482e-04]]

  [[ 7.65980920e-04]
   [ 1.00983493e-03]
   [ 7.38106843e-04]
   ...
   [ 9.59600380e-04]
   [ 7.63182063e-04]
   [ 7.92920589e-04]]

  [[ 9.67128784e-04]
   [ 9.69112851e-04]
   [ 1.08430302e-03]
   ...
   [ 1.08620292e-03]
 

[[[[0.00070343]
   [0.00064268]
   [0.00074533]
   ...
   [0.00011524]
   [0.00087043]
   [0.00085011]]

  [[0.00061678]
   [0.00076214]
   [0.00068848]
   ...
   [0.00064558]
   [0.00069114]
   [0.0008539 ]]

  [[0.00110219]
   [0.00125096]
   [0.00054457]
   ...
   [0.00043586]
   [0.00137286]
   [0.00070395]]

  ...

  [[0.00089359]
   [0.00092924]
   [0.00056392]
   ...
   [0.00053941]
   [0.00074914]
   [0.00073835]]

  [[0.00093624]
   [0.00084158]
   [0.00075216]
   ...
   [0.00066318]
   [0.00107971]
   [0.00083067]]

  [[0.00094653]
   [0.00092973]
   [0.00066893]
   ...
   [0.00037997]
   [0.00085851]
   [0.00087047]]]]
[[[[0.00071372]
   [0.00079644]
   [0.00068555]
   ...
   [0.00064641]
   [0.00067391]
   [0.0011855 ]]

  [[0.00070216]
   [0.00072987]
   [0.0008599 ]
   ...
   [0.00086124]
   [0.00076614]
   [0.0009905 ]]

  [[0.00080484]
   [0.00081449]
   [0.00044684]
   ...
   [0.00054359]
   [0.00106263]
   [0.00111043]]

  ...

  [[0.00086537]
   [0.00083724]
   [0.00

[[[[0.00092871]
   [0.0009936 ]
   [0.0009987 ]
   ...
   [0.0010647 ]
   [0.00095405]
   [0.00065181]]

  [[0.000828  ]
   [0.00094875]
   [0.00091432]
   ...
   [0.00092912]
   [0.00107487]
   [0.0003777 ]]

  [[0.0007571 ]
   [0.00090405]
   [0.0009158 ]
   ...
   [0.00066936]
   [0.00102608]
   [0.00064736]]

  ...

  [[0.0008964 ]
   [0.00081447]
   [0.00081975]
   ...
   [0.00070672]
   [0.00085179]
   [0.00079412]]

  [[0.00100536]
   [0.00086405]
   [0.00084043]
   ...
   [0.00060561]
   [0.0008822 ]
   [0.00080112]]

  [[0.00093291]
   [0.00098098]
   [0.00094118]
   ...
   [0.00065387]
   [0.00080925]
   [0.00093327]]]]
[[[[8.5975189e-04]
   [9.4037375e-04]
   [5.7982333e-04]
   ...
   [9.2626957e-04]
   [6.6229806e-04]
   [6.1140949e-04]]

  [[6.4526097e-04]
   [6.8176095e-04]
   [5.5031030e-04]
   ...
   [9.0184517e-04]
   [9.6640451e-04]
   [8.8322279e-04]]

  [[5.4443278e-04]
   [6.1901199e-04]
   [9.0291194e-04]
   ...
   [2.9581191e-05]
   [7.1774150e-04]
   [1.0390593e

ValueError: arrays must all be same length

In [17]:
data = pd.read_csv('CSV/A_on_A_test.csv')
y_true = data['y_true']
y_pred = data['y_pred']

In [18]:
data.head()

Unnamed: 0                                            name    y_pred  \
0           0    data\part_A_final/test_data\images\IMG_1.jpg  4.085224   
1           1   data\part_A_final/test_data\images\IMG_10.jpg  4.769192   
2           2  data\part_A_final/test_data\images\IMG_100.jpg  1.840265   
3           3  data\part_A_final/test_data\images\IMG_101.jpg  3.703334   
4           4  data\part_A_final/test_data\images\IMG_102.jpg  0.699472   

       y_true  
0  171.829422  
1  497.063629  
2  383.926056  
3  210.397263  
4  217.376938

In [21]:
ans = mean_absolute_error(np.array(y_true),np.array(y_pred))

In [22]:
print("MAE : " , ans )

MAE :  426.10253292977154


In [207]:
data = pd.read_csv('CSV/B_on_B_test.csv' , sep='\t')
y_true = data['y_true']
y_pred = data['y_pred']

In [208]:
ans = mean_absolute_error(np.array(y_true),np.array(y_pred))

In [209]:
print("MAE : " , ans )

MAE :  11.001472832281378


In [25]:
t

AttributeError: 'Sequential' object has no attribute 'history'